# Generated by Django 4.2.16 on 2024-12-05 10:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Task_user_login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='reports_to',
            field=models.ForeignKey(blank=True, default=None, limit_choices_to=models.Q(('groups__name', 'Admin'), ('groups__name', 'Project_Manager'), ('groups__name', 'HR_Admin'), _connector='OR'), null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL),
        ),
    ]
