# Generated by Django 4.2.16 on 2024-12-06 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('Task_user_login', '0003_remove_usermodel_groups_usermodel_groups'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='groups',
        ),
        migrations.AddField(
            model_name='usermodel',
            name='groups',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Custom_User_Group', to='auth.group'),
        ),
    ]
