# Generated by Django 4.2.16 on 2024-12-05 10:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Taskmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, max_length=2000, null=True)),
                ('due_date', models.DateField(auto_now=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('Done', 'Done'), ('InProgress', 'Inprogress'), ('Backlogged', 'Backlogged')], max_length=50)),
                ('priority', models.CharField(blank=True, choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], max_length=50)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('deactive_time', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_assigned_to', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(limit_choices_to=models.Q(('groups__name', 'Project_Manager'), ('groups__name', 'Admin'), ('groups__name', 'HR_Admin'), _connector='OR'), on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
