# Generated by Django 4.2.16 on 2024-12-05 10:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Task_app', '0002_alter_taskmodel_due_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskmodel',
            name='assigned_to',
        ),
        migrations.AddField(
            model_name='taskmodel',
            name='assigned_to',
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name='user_assigned_to', to=settings.AUTH_USER_MODEL),
        ),
    ]
