# Generated by Django 4.2.16 on 2024-12-08 05:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Task_app', '0003_remove_taskmodel_assigned_to_taskmodel_assigned_to'),
    ]

    operations = [
        migrations.CreateModel(
            name='BacklogsTaskModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extend_due_date', models.DateTimeField(blank=True, null=True)),
                ('moved_to_backlog_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('comments', models.TextField(blank=True, max_length=500, null=True)),
                ('reassigned_to', models.ManyToManyField(blank=True, related_name='reassigned_to', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='back_log_task', to='Task_app.taskmodel')),
            ],
        ),
    ]
