# Generated by Django 4.2.16 on 2024-12-08 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Task_app', '0004_backlogstaskmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='backlogstaskmodel',
            old_name='extend_due_date',
            new_name='original_due_date',
        ),
    ]
