# Generated by Django 4.2.16 on 2024-12-08 06:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Task_app', '0005_rename_extend_due_date_backlogstaskmodel_original_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='backlogstaskmodel',
            name='assigned_to',
            field=models.ManyToManyField(blank=True, default=None, related_name='user_Back_assigned_to', to=settings.AUTH_USER_MODEL),
        ),
    ]
