# Generated by Django 4.2.16 on 2024-12-08 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Task_app', '0006_backlogstaskmodel_assigned_to'),
    ]

    operations = [
        migrations.RenameField(
            model_name='backlogstaskmodel',
            old_name='assigned_to',
            new_name='assigned_to_due',
        ),
    ]
