# Generated by Django 4.2.16 on 2024-12-08 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Task_app', '0007_rename_assigned_to_backlogstaskmodel_assigned_to_due'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmodel',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
