# Generated by Django 4.2.16 on 2024-12-08 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Task_app', '0008_alter_taskmodel_due_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='backlogstaskmodel',
            name='reassigned_to',
        ),
    ]
